// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fsg.genealogy.domain;

import com.fsg.genealogy.domain.Timeline;

privileged aspect Timeline_Roo_JavaBean {
    
    public String Timeline.getData() {
        return this.data;
    }
    
    public void Timeline.setData(String data) {
        this.data = data;
    }
    
}
