// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fsg.storify.readservice.timeline;

import com.fsg.storify.readservice.timeline.Family;

privileged aspect Family_Roo_JavaBean {
    
    public String Family.getName() {
        return this.name;
    }
    
    public void Family.setName(String name) {
        this.name = name;
    }
    
}
