// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fsg.storify.readservice.timeline;

import com.fsg.storify.readservice.timeline.Timeline;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Timeline_Roo_Configurable {
    
    declare @type: TimelineAPI: @Configurable;
    
}
